Configuring Github Actions workflows to deply and run tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,8 @@ jobs:
     runs-on: ubuntu-latest
     env:
       FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+      # Overriding threshold to 5s to stop random CI failures on public APIs
+      MAX_RESPONSE_TIME: 5.0
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -38,30 +40,35 @@ jobs:
           pip install -r requirements.txt
 
       - name: Run Tests
+        id: run_tests
         run: |
-          mkdir -p allure-results
+          # 1. Create fresh directories
+          mkdir -p test_results allure-results
           
-          # Initialize base command
-          CMD="pytest tests/ --alluredir=allure-results -v"
+          # 2. Build command dynamically
+          # We do NOT use '|| true' here because we want the CI job to correctly show as 'Failed' if tests fail.
+          # The artifacts will still upload because the 'Upload Artifacts' step uses 'if: always()'.
+          CMD="pytest tests/ --alluredir=allure-results --junitxml=test_results/results.xml --html=test_results/report.html --self-contained-html -v"
           
-          # Conditionally add the flag ONLY if it's not 'none'
           if [ "${{ github.event.inputs.env }}" != "none" ]; then
             CMD="$CMD --env=${{ github.event.inputs.env }}"
           fi
           
-          # Execute the command
+          # 3. Execute
           $CMD
 
       - name: Generate Allure Report
-        if: always()
+        if: always() # Run even if tests failed
         run: |
           sudo apt-get update && sudo apt-get install -y default-jdk
           npm install -g allure-commandline
           allure generate allure-results --clean -o allure-report
 
       - name: Upload Artifacts
-        if: always()
+        if: always() # This ensures reports are uploaded even on test failure
         uses: actions/upload-artifact@v4
         with:
           name: qa-artifacts
-          path: allure-report/
+          path: |
+            test_results/
+            allure-report/
